# Variant Annotator Configuration

input:
  vcf_file: "data/clinvar_test.vcf"
  max_variants: null # Set to null for no limit, or specify an integer to limit the number of variants parsed

clinvar:
  # Clinical significance levels to include in the report
  include_significance:
    - "Pathogenic"
    - "Likely pathogenic"
    - "Uncertain significance"
    - "Likely benign"
    - "Benign"

priority_levels:
  # Significance levels that get flagged as high priority in the report
  high priority:
    - "pathogenic"
    - "likely pathogenic"
  medium priority:
    - "conflicting classifications of pathogenicity"
    - "uncertain significance"
  low priority:
    - "likely benign"
    - "benign"
  pharmacogenomics:
    - "drug response"

report_file: "report.tsv"